---
  POSTGRES_SERVER: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: cells-backend
  POSTGRES_PASSWORD: TO_REPLACE
  POSTGRES_DB: cells-db
  GCP_PROJECT_ID: "TO_REPLACE"
  GCP_PROJECT_LOCATION: europe-west4